// Generated by Bisonc++ V4.09.02 on Mon, 11 Jan 2016 01:06:14 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {293, 3}, // 1: start ->  program data main
     {294, 3}, // 2: program (PROGRAM) ->  PROGRAM IDENTIFIER END_STATEMENT
     {295, 0}, // 3: data ->  <empty>
     {295, 3}, // 4: data (DATA) ->  DATA DATA_SUFIX one_or_more_declarations
     {297, 2}, // 5: one_or_more_declarations (END_STATEMENT) ->  declaration END_STATEMENT
     {297, 3}, // 6: one_or_more_declarations (DATA_SEPARATOR) ->  declaration DATA_SEPARATOR one_or_more_declarations
     {298, 3}, // 7: declaration (IDENTIFIER) ->  IDENTIFIER TYPE TYPE_I
     {298, 3}, // 8: declaration (IDENTIFIER) ->  IDENTIFIER TYPE TYPE_B
     {296, 0}, // 9: main ->  <empty>
     {296, 1}, // 10: main ->  one_or_more_statements
     {299, 2}, // 11: one_or_more_statements (END_STATEMENT) ->  statement END_STATEMENT
     {299, 3}, // 12: one_or_more_statements (END_STATEMENT) ->  statement END_STATEMENT one_or_more_statements
     {300, 1}, // 13: statement ->  move
     {300, 1}, // 14: statement ->  read
     {300, 1}, // 15: statement ->  write
     {300, 1}, // 16: statement ->  add
     {300, 1}, // 17: statement ->  substract
     {300, 1}, // 18: statement ->  multiply
     {300, 1}, // 19: statement ->  divide
     {300, 1}, // 20: statement ->  mod
     {300, 1}, // 21: statement ->  while
     {300, 1}, // 22: statement ->  if
     {311, 1}, // 23: expression (IDENTIFIER) ->  IDENTIFIER
     {311, 1}, // 24: expression (IDENTIFIER_I) ->  IDENTIFIER_I
     {311, 1}, // 25: expression (IDENTIFIER_B_TRUE) ->  IDENTIFIER_B_TRUE
     {311, 1}, // 26: expression (IDENTIFIER_B_FALSE) ->  IDENTIFIER_B_FALSE
     {311, 3}, // 27: expression (AND) ->  expression AND expression
     {311, 3}, // 28: expression (OR) ->  expression OR expression
     {311, 2}, // 29: expression (NOT) ->  NOT expression
     {311, 3}, // 30: expression (LEFT_BRACKET) ->  LEFT_BRACKET expression RIGHT_BRACKET
     {311, 3}, // 31: expression (EQUAL) ->  expression EQUAL expression
     {311, 3}, // 32: expression (LESSER_THAN) ->  expression LESSER_THAN expression
     {311, 3}, // 33: expression (GREATER_THAN) ->  expression GREATER_THAN expression
     {301, 4}, // 34: move (MOVE) ->  MOVE expression TO IDENTIFIER
     {302, 3}, // 35: read (READ) ->  READ TO IDENTIFIER
     {303, 2}, // 36: write (WRITE) ->  WRITE expression
     {304, 4}, // 37: add (ADD) ->  ADD expression TO IDENTIFIER
     {305, 4}, // 38: substract (SUBTRACT) ->  SUBTRACT expression FROM IDENTIFIER
     {306, 4}, // 39: multiply (MULTIPLY) ->  MULTIPLY IDENTIFIER BY expression
     {307, 4}, // 40: divide (DIVIDE) ->  DIVIDE IDENTIFIER BY expression
     {308, 6}, // 41: mod (MOD) ->  MOD IDENTIFIER BY expression TO IDENTIFIER
     {309, 5}, // 42: while (WHILE) ->  WHILE expression END_STATEMENT one_or_more_statements ENDWHILE
     {310, 5}, // 43: if (IF) ->  IF expression END_STATEMENT one_or_more_statements zero_or_one_else
     {312, 1}, // 44: zero_or_one_else (ENDIF) ->  ENDIF
     {312, 4}, // 45: zero_or_one_else (ELSE) ->  ELSE END_STATEMENT one_or_more_statements ENDIF
     {313, 1}, // 46: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },           
    { {       293}, { 1} }, // start  
    { {       294}, { 2} }, // program
    { {       258}, { 3} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  3} },        
    { {     295}, {  4} }, // data
    { {     259}, {  5} }, // DATA
    { {       0}, { -3} },        
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },              
    { {       287}, { 6} }, // IDENTIFIER
    { {         0}, { 0} },              
};

SR__ s_4[] =
{
    { { REQ_DEF}, { 24} },                          
    { {     296}, {  7} }, // main                  
    { {     299}, {  8} }, // one_or_more_statements
    { {     300}, {  9} }, // statement             
    { {     301}, { 10} }, // move                  
    { {     302}, { 11} }, // read                  
    { {     303}, { 12} }, // write                 
    { {     304}, { 13} }, // add                   
    { {     305}, { 14} }, // substract             
    { {     306}, { 15} }, // multiply              
    { {     307}, { 16} }, // divide                
    { {     308}, { 17} }, // mod                   
    { {     309}, { 18} }, // while                 
    { {     310}, { 19} }, // if                    
    { {     276}, { 20} }, // MOVE                  
    { {     274}, { 21} }, // READ                  
    { {     275}, { 22} }, // WRITE                 
    { {     277}, { 23} }, // ADD                   
    { {     278}, { 24} }, // SUBTRACT              
    { {     279}, { 25} }, // MULTIPLY              
    { {     280}, { 26} }, // DIVIDE                
    { {     281}, { 27} }, // MOD                   
    { {     265}, { 28} }, // WHILE                 
    { {     267}, { 29} }, // IF                    
    { {       0}, { -9} },                          
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       260}, { 30} }, // DATA_SUFIX
    { {         0}, {  0} },              
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },                 
    { {       257}, { 31} }, // END_STATEMENT
    { {         0}, {  0} },                 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },                 
    { {       257}, { 32} }, // END_STATEMENT
    { {         0}, {  0} },                 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 33} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       271}, { 40} }, // TO
    { {         0}, {  0} },      
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 41} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 42} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 43} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 44} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 45} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 46} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 47} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 48} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  4} },                            
    { {       297}, { 49} }, // one_or_more_declarations
    { {       298}, { 50} }, // declaration             
    { {       287}, { 51} }, // IDENTIFIER              
    { {         0}, {  0} },                            
};

SR__ s_31[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_32[] =
{
    { { REQ_DEF}, {  23} },                          
    { {     299}, {  52} }, // one_or_more_statements
    { {     300}, {   9} }, // statement             
    { {     301}, {  10} }, // move                  
    { {     302}, {  11} }, // read                  
    { {     303}, {  12} }, // write                 
    { {     304}, {  13} }, // add                   
    { {     305}, {  14} }, // substract             
    { {     306}, {  15} }, // multiply              
    { {     307}, {  16} }, // divide                
    { {     308}, {  17} }, // mod                   
    { {     309}, {  18} }, // while                 
    { {     310}, {  19} }, // if                    
    { {     276}, {  20} }, // MOVE                  
    { {     274}, {  21} }, // READ                  
    { {     275}, {  22} }, // WRITE                 
    { {     277}, {  23} }, // ADD                   
    { {     278}, {  24} }, // SUBTRACT              
    { {     279}, {  25} }, // MULTIPLY              
    { {     280}, {  26} }, // DIVIDE                
    { {     281}, {  27} }, // MOD                   
    { {     265}, {  28} }, // WHILE                 
    { {     267}, {  29} }, // IF                    
    { {       0}, { -11} },                          
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       271}, { 53} }, // TO          
    { {       288}, { 54} }, // AND         
    { {       289}, { 55} }, // OR          
    { {       290}, { 56} }, // EQUAL       
    { {       291}, { 57} }, // LESSER_THAN 
    { {       292}, { 58} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 59} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 60} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 61} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_41[] =
{
    { { REQ_DEF}, {   6} },                
    { {     288}, {  54} }, // AND         
    { {     289}, {  55} }, // OR          
    { {     290}, {  56} }, // EQUAL       
    { {     291}, {  57} }, // LESSER_THAN 
    { {     292}, {  58} }, // GREATER_THAN
    { {       0}, { -36} },                
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       271}, { 62} }, // TO          
    { {       288}, { 54} }, // AND         
    { {       289}, { 55} }, // OR          
    { {       290}, { 56} }, // EQUAL       
    { {       291}, { 57} }, // LESSER_THAN 
    { {       292}, { 58} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       273}, { 63} }, // FROM        
    { {       288}, { 54} }, // AND         
    { {       289}, { 55} }, // OR          
    { {       290}, { 56} }, // EQUAL       
    { {       291}, { 57} }, // LESSER_THAN 
    { {       292}, { 58} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       272}, { 64} }, // BY
    { {         0}, {  0} },      
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       272}, { 65} }, // BY
    { {         0}, {  0} },      
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       272}, { 66} }, // BY
    { {         0}, {  0} },      
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       257}, { 67} }, // END_STATEMENT
    { {       288}, { 54} }, // AND          
    { {       289}, { 55} }, // OR           
    { {       290}, { 56} }, // EQUAL        
    { {       291}, { 57} }, // LESSER_THAN  
    { {       292}, { 58} }, // GREATER_THAN 
    { {         0}, {  0} },                 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       257}, { 68} }, // END_STATEMENT
    { {       288}, { 54} }, // AND          
    { {       289}, { 55} }, // OR           
    { {       290}, { 56} }, // EQUAL        
    { {       291}, { 57} }, // LESSER_THAN  
    { {       292}, { 58} }, // GREATER_THAN 
    { {         0}, {  0} },                 
};

SR__ s_49[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       257}, { 69} }, // END_STATEMENT 
    { {       261}, { 70} }, // DATA_SEPARATOR
    { {         0}, {  0} },                  
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       262}, { 71} }, // TYPE
    { {         0}, {  0} },        
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 72} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 73} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 74} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 75} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 76} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 77} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   6} },                
    { {     288}, {  54} }, // AND         
    { {     289}, {  55} }, // OR          
    { {     290}, {  56} }, // EQUAL       
    { {     291}, {  57} }, // LESSER_THAN 
    { {     292}, {  58} }, // GREATER_THAN
    { {       0}, { -29} },                
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  7} },                 
    { {       286}, { 78} }, // RIGHT_BRACKET
    { {       288}, { 54} }, // AND          
    { {       289}, { 55} }, // OR           
    { {       290}, { 56} }, // EQUAL        
    { {       291}, { 57} }, // LESSER_THAN  
    { {       292}, { 58} }, // GREATER_THAN 
    { {         0}, {  0} },                 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 79} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 80} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 81} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 82} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  8} },                      
    { {       311}, { 83} }, // expression        
    { {       287}, { 34} }, // IDENTIFIER        
    { {       282}, { 35} }, // IDENTIFIER_I      
    { {       283}, { 36} }, // IDENTIFIER_B_TRUE 
    { {       284}, { 37} }, // IDENTIFIER_B_FALSE
    { {       270}, { 38} }, // NOT               
    { {       285}, { 39} }, // LEFT_BRACKET      
    { {         0}, {  0} },                      
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 23} },                          
    { {       299}, { 84} }, // one_or_more_statements
    { {       300}, {  9} }, // statement             
    { {       301}, { 10} }, // move                  
    { {       302}, { 11} }, // read                  
    { {       303}, { 12} }, // write                 
    { {       304}, { 13} }, // add                   
    { {       305}, { 14} }, // substract             
    { {       306}, { 15} }, // multiply              
    { {       307}, { 16} }, // divide                
    { {       308}, { 17} }, // mod                   
    { {       309}, { 18} }, // while                 
    { {       310}, { 19} }, // if                    
    { {       276}, { 20} }, // MOVE                  
    { {       274}, { 21} }, // READ                  
    { {       275}, { 22} }, // WRITE                 
    { {       277}, { 23} }, // ADD                   
    { {       278}, { 24} }, // SUBTRACT              
    { {       279}, { 25} }, // MULTIPLY              
    { {       280}, { 26} }, // DIVIDE                
    { {       281}, { 27} }, // MOD                   
    { {       265}, { 28} }, // WHILE                 
    { {       267}, { 29} }, // IF                    
    { {         0}, {  0} },                          
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, { 23} },                          
    { {       299}, { 85} }, // one_or_more_statements
    { {       300}, {  9} }, // statement             
    { {       301}, { 10} }, // move                  
    { {       302}, { 11} }, // read                  
    { {       303}, { 12} }, // write                 
    { {       304}, { 13} }, // add                   
    { {       305}, { 14} }, // substract             
    { {       306}, { 15} }, // multiply              
    { {       307}, { 16} }, // divide                
    { {       308}, { 17} }, // mod                   
    { {       309}, { 18} }, // while                 
    { {       310}, { 19} }, // if                    
    { {       276}, { 20} }, // MOVE                  
    { {       274}, { 21} }, // READ                  
    { {       275}, { 22} }, // WRITE                 
    { {       277}, { 23} }, // ADD                   
    { {       278}, { 24} }, // SUBTRACT              
    { {       279}, { 25} }, // MULTIPLY              
    { {       280}, { 26} }, // DIVIDE                
    { {       281}, { 27} }, // MOD                   
    { {       265}, { 28} }, // WHILE                 
    { {       267}, { 29} }, // IF                    
    { {         0}, {  0} },                          
};

SR__ s_69[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  4} },                            
    { {       297}, { 86} }, // one_or_more_declarations
    { {       298}, { 50} }, // declaration             
    { {       287}, { 51} }, // IDENTIFIER              
    { {         0}, {  0} },                            
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       263}, { 87} }, // TYPE_I
    { {       264}, { 88} }, // TYPE_B
    { {         0}, {  0} },          
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_75[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_76[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_77[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_81[] =
{
    { { REQ_DEF}, {   6} },                
    { {     288}, {  54} }, // AND         
    { {     289}, {  55} }, // OR          
    { {     290}, {  56} }, // EQUAL       
    { {     291}, {  57} }, // LESSER_THAN 
    { {     292}, {  58} }, // GREATER_THAN
    { {       0}, { -39} },                
};

SR__ s_82[] =
{
    { { REQ_DEF}, {   6} },                
    { {     288}, {  54} }, // AND         
    { {     289}, {  55} }, // OR          
    { {     290}, {  56} }, // EQUAL       
    { {     291}, {  57} }, // LESSER_THAN 
    { {     292}, {  58} }, // GREATER_THAN
    { {       0}, { -40} },                
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  7} },                
    { {       271}, { 89} }, // TO          
    { {       288}, { 54} }, // AND         
    { {       289}, { 55} }, // OR          
    { {       290}, { 56} }, // EQUAL       
    { {       291}, { 57} }, // LESSER_THAN 
    { {       292}, { 58} }, // GREATER_THAN
    { {         0}, {  0} },                
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       266}, { 90} }, // ENDWHILE
    { {         0}, {  0} },            
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       312}, { 91} }, // zero_or_one_else
    { {       269}, { 92} }, // ENDIF           
    { {       268}, { 93} }, // ELSE            
    { {         0}, {  0} },                    
};

SR__ s_86[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       287}, { 94} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {  2} },                 
    { {       257}, { 95} }, // END_STATEMENT
    { {         0}, {  0} },                 
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, { 23} },                          
    { {       299}, { 96} }, // one_or_more_statements
    { {       300}, {  9} }, // statement             
    { {       301}, { 10} }, // move                  
    { {       302}, { 11} }, // read                  
    { {       303}, { 12} }, // write                 
    { {       304}, { 13} }, // add                   
    { {       305}, { 14} }, // substract             
    { {       306}, { 15} }, // multiply              
    { {       307}, { 16} }, // divide                
    { {       308}, { 17} }, // mod                   
    { {       309}, { 18} }, // while                 
    { {       310}, { 19} }, // if                    
    { {       276}, { 20} }, // MOVE                  
    { {       274}, { 21} }, // READ                  
    { {       275}, { 22} }, // WRITE                 
    { {       277}, { 23} }, // ADD                   
    { {       278}, { 24} }, // SUBTRACT              
    { {       279}, { 25} }, // MULTIPLY              
    { {       280}, { 26} }, // DIVIDE                
    { {       281}, { 27} }, // MOD                   
    { {       265}, { 28} }, // WHILE                 
    { {       267}, { 29} }, // IF                    
    { {         0}, {  0} },                          
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       269}, { 97} }, // ENDIF
    { {         0}, {  0} },         
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 52 "grammar.y"
        {
         std::cout << "start -> program data main" << std::endl;
         }
        break;

        case 2:
#line 62 "grammar.y"
        {
         std::cout << "program -> PROGRAM IDENTIFIER END_STATEMENT" << std::endl;
         }
        break;

        case 3:
#line 72 "grammar.y"
        {
         std::cout << "data -> skip" << std::endl;
         }
        break;

        case 4:
#line 77 "grammar.y"
        {
         std::cout << "data -> DATA DATA_SUFIX one_or_more_declarations" << std::endl;
         }
        break;

        case 5:
#line 84 "grammar.y"
        {
         std::cout << "data -> declaration END_STATEMENT" << std::endl;
         }
        break;

        case 6:
#line 89 "grammar.y"
        {
         std::cout << "data -> declaration DATA_SEPARATOR one_or_more_declarations" << std::endl;
         }
        break;

        case 7:
#line 96 "grammar.y"
        {
         std::cout << "data -> IDENTIFIER TYPE TYPE_I" << std::endl;
         }
        break;

        case 8:
#line 101 "grammar.y"
        {
         std::cout << "data -> IDENTIFIER TYPE TYPE_B" << std::endl;
         }
        break;

        case 9:
#line 111 "grammar.y"
        {
         std::cout << "main -> skip" << std::endl;
         }
        break;

        case 10:
#line 116 "grammar.y"
        {
         std::cout << "main -> one_or_more_statements" << std::endl;
         }
        break;

        case 11:
#line 123 "grammar.y"
        {
         std::cout << "main -> statement END_STATEMENT" << std::endl;
         }
        break;

        case 12:
#line 128 "grammar.y"
        {
         std::cout << "main -> statement END_STATEMENT one_or_more_statements" << std::endl;
         }
        break;

        case 13:
#line 135 "grammar.y"
        {
         std::cout << "statement -> move" << std::endl;
         }
        break;

        case 14:
#line 140 "grammar.y"
        {
         std::cout << "statement -> read" << std::endl;
         }
        break;

        case 15:
#line 145 "grammar.y"
        {
         std::cout << "statement -> write" << std::endl;
         }
        break;

        case 16:
#line 150 "grammar.y"
        {
         std::cout << "statement -> add" << std::endl;
         }
        break;

        case 17:
#line 155 "grammar.y"
        {
         std::cout << "statement -> substract" << std::endl;
         }
        break;

        case 18:
#line 160 "grammar.y"
        {
         std::cout << "statement -> multiply" << std::endl;
         }
        break;

        case 19:
#line 165 "grammar.y"
        {
         std::cout << "statement -> divide" << std::endl;
         }
        break;

        case 20:
#line 170 "grammar.y"
        {
         std::cout << "statement -> mod" << std::endl;
         }
        break;

        case 21:
#line 175 "grammar.y"
        {
         std::cout << "statement -> while" << std::endl;
         }
        break;

        case 22:
#line 180 "grammar.y"
        {
         std::cout << "statement -> if" << std::endl;
         }
        break;

        case 23:
#line 187 "grammar.y"
        {
         std::cout << "expression -> IDENTIFIER" << std::endl;
         }
        break;

        case 24:
#line 192 "grammar.y"
        {
         std::cout << "expression -> IDENTIFIER_I" << std::endl;
         }
        break;

        case 25:
#line 197 "grammar.y"
        {
         std::cout << "expression -> IDENTIFIER_B_TRUE" << std::endl;
         }
        break;

        case 26:
#line 202 "grammar.y"
        {
         std::cout << "expression -> IDENTIFIER_B_FALSE" << std::endl;
         }
        break;

        case 27:
#line 207 "grammar.y"
        {
         std::cout << "expression -> expression AND expression" << std::endl;
         }
        break;

        case 28:
#line 212 "grammar.y"
        {
         std::cout << "expression -> expression OR expression" << std::endl;
         }
        break;

        case 29:
#line 217 "grammar.y"
        {
         std::cout << "expression -> NOT expression" << std::endl;
         }
        break;

        case 30:
#line 222 "grammar.y"
        {
         std::cout << "expression -> LEFT_BRACKET expression RIGHT_BRACKET" << std::endl;
         }
        break;

        case 31:
#line 227 "grammar.y"
        {
         std::cout << "expression -> expression EQUAL expression" << std::endl;
         }
        break;

        case 32:
#line 232 "grammar.y"
        {
         std::cout << "expression -> expression LESSER_THAN expression" << std::endl;
         }
        break;

        case 33:
#line 237 "grammar.y"
        {
         std::cout << "expression -> expression GREATER_THAN expression" << std::endl;
         }
        break;

        case 34:
#line 244 "grammar.y"
        {
         std::cout << "move -> MOVE expression TO IDENTIFIER" << std::endl;
         }
        break;

        case 35:
#line 251 "grammar.y"
        {
         std::cout << "read -> READ TO IDENTIFIER" << std::endl;
         }
        break;

        case 36:
#line 258 "grammar.y"
        {
         std::cout << "write -> WRITE expression" << std::endl;
         }
        break;

        case 37:
#line 265 "grammar.y"
        {
         std::cout << "add -> ADD expression TO IDENTIFIER" << std::endl;
         }
        break;

        case 38:
#line 272 "grammar.y"
        {
         std::cout << "substract -> SUBTRACT expression FROM IDENTIFIER" << std::endl;
         }
        break;

        case 39:
#line 279 "grammar.y"
        {
         std::cout << "multiply -> MULTIPLY IDENTIFIER BY expression" << std::endl;
         }
        break;

        case 40:
#line 286 "grammar.y"
        {
         std::cout << "divide -> DIVIDE IDENTIFIER BY expression" << std::endl;
         }
        break;

        case 41:
#line 293 "grammar.y"
        {
         std::cout << "mod -> MOD IDENTIFIER BY expression TO IDENTIFIER" << std::endl;
         }
        break;

        case 42:
#line 300 "grammar.y"
        {
         std::cout << "while -> WHILE expression END_STATEMENT one_or_more_statements ENDWHILE" << std::endl;
         }
        break;

        case 43:
#line 307 "grammar.y"
        {
         std::cout << "if -> IF expression END_STATEMENT one_or_more_statements zero_or_one_else" << std::endl;
         }
        break;

        case 44:
#line 314 "grammar.y"
        {
         std::cout << "zero_or_one_else -> ENDIF" << std::endl;
         }
        break;

        case 45:
#line 319 "grammar.y"
        {
         std::cout << "zero_or_one_else -> ELSE END_STATEMENT one_or_more_statements ENDIF" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



